# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'tabarato' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tabarato
  
  pod 'GooglePlaces', '2.1'
  pod 'GooglePlacePicker', '2.1'
  pod 'GoogleMaps', '2.1'

end
